# Generated by Django 3.2.6 on 2021-08-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='percent',
            field=models.IntegerField(verbose_name='Размер скидки'),
        ),
    ]
